services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres3
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - pgtables:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./sql/init.sql:/docker-entrypoint-initdb.d/02-init.sql:ro


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin3
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "${PGADMIN_DEFAULT_PORT}:80"

    depends_on:
      - postgres


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: weather-app

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      - postgres


  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow
    restart: always

    user: "${AIRFLOW_UID:-1000}:0"

    env_file:
    - .env

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://weather_user:${POSTGRES_PASSWORD}@postgres:5432/airflow
      PYTHONPATH: /opt/airflow

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./extraction:/opt/airflow/extraction
      - ./transformation:/opt/airflow/transformation
      - ./load:/opt/airflow/load
      - ./data:/opt/airflow/data
      - ./sources:/opt/airflow/sources

    depends_on:
      - postgres

    command: standalone


volumes:
  pgtables: